name: "Auto Version Tag"
description: "Create release tags based on Cargo.toml/package.json/pyproject.toml versions."
author: tamasfe
inputs:
  paths:
    description: "space-separated paths to search for packages in."
    default: "."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "tag"
  color: "blue"
